# Stage 1: Build the Angular application
FROM node:20 AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install --force
COPY frontend/ ./
RUN npm run build --prod

# Stage 2: Serve the application from Nginx
FROM nginx:alpine
COPY --from=build /app/dist/frontend-app/browser /usr/share/nginx/html
EXPOSE 80
