FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY backend/ ./backend/
WORKDIR /app/backend

# Install dotnet-ef global tool
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool restore
# Restore dependencies
RUN dotnet tool install --global dotnet-ef --version 8.0.0

# Entrypoint to run migrations
ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "backend.csproj", "--startup-project", "backend.csproj"]